import 'package:alquran-database-indonesia/erd_surah.dart';

final rawSurah = {
  Surah(
    id: 1,
    arti: "Pembukaan",
    asma: "الفاتحة",
    jumlahAyat: 7,
    keyword: "al fatihah",
    keterangan: "",
    namaSurah: "Al Fatihah",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 5
  ),
  Surah(
    id: 2,
    arti: "Sapi Betina",
    asma: "البقرة",
    jumlahAyat: 286,
    keyword: "al baqarah baqoroh",
    keterangan: "",
    namaSurah: "Al Baqarah",
    jumlahRukuk: 40,
    type: "madinah",
    urut: 87
  ),
  Surah(
    id: 3,
    arti: "Keluarga Imran",
    asma: "آل عمران",
    jumlahAyat: 200,
    keyword: "ali imran imron",
    keterangan: "",
    namaSurah: "Ali Imran",
    jumlahRukuk: 20,
    type: "madinah",
    urut: 89
  ),
  Surah(
    id: 4,
    arti: "Wanita",
    asma: "النساء",
    jumlahAyat: 176,
    keyword: "an nisa",
    keterangan: "",
    namaSurah: "An Nisaa",
    jumlahRukuk: 24,
    type: "madinah",
    urut: 92
  ),
  Surah(
    id: 5,
    arti: "Hidangan",
    asma: "المائدة",
    jumlahAyat: 120,
    keyword: "al maidah",
    keterangan: "",
    namaSurah: "Al Maidah",
    jumlahRukuk: 16,
    type: "madinah",
    urut: 112
  ),
  Surah(
    id: 6,
    arti: "Binatang Ternak",
    asma: "الأنعام",
    jumlahAyat: 165,
    keyword: "al anam",
    keterangan: "",
    namaSurah: "Al An'am",
    jumlahRukuk: 20,
    type: "mekah",
    urut: 55
  ),
  Surah(
    id: 7,
    arti: "Tempat Tertinggi",
    asma: "الأعراف",
    jumlahAyat: 206,
    keyword: "al araf",
    keterangan: "",
    namaSurah: "Al A'raf",
    jumlahRukuk: 24,
    type: "mekah",
    urut: 39
  ),
  Surah(
    id: 8,
    arti: "Harta Rampasan Perang",
    asma: "الأنفال",
    jumlahAyat: 75,
    keyword: "al anfal",
    keterangan: "",
    namaSurah: "Al Anfaal",
    jumlahRukuk: 10,
    type: "madinah",
    urut: 88
  ),
  Surah(
    id: 9,
    arti: "Pengampunan",
    asma: "التوبة",
    jumlahAyat: 129,
    keyword: "at taubah",
    keterangan: "",
    namaSurah: "At Taubah",
    jumlahRukuk: 16,
    type: "madinah",
    urut: 113
  ),
  Surah(
    id: 10,
    arti: "Yunus",
    asma: "يونس",
    jumlahAyat: 109,
    keyword: "yunus",
    keterangan: "",
    namaSurah: "Yunus",
    jumlahRukuk: 11,
    type: "mekah",
    urut: 51
  ),
  Surah(
    id: 11,
    arti: "Hud",
    asma: "هود",
    jumlahAyat: 123,
    keyword: "hud huud",
    keterangan: "",
    namaSurah: "Huud",
    jumlahRukuk: 10,
    type: "mekah",
    urut: 52
  ),
  Surah(
    id: 12,
    arti: "Yusuf",
    asma: "يوسف",
    jumlahAyat: 111,
    keyword: "yusuf",
    keterangan: "",
    namaSurah: "Yusuf",
    jumlahRukuk: 12,
    type: "mekah",
    urut: 53
  ),
  Surah(
    id: 13,
    arti: "Guruh",
    asma: "الرعد",
    jumlahAyat: 43,
    keyword: "ar rad",
    keterangan: "",
    namaSurah: "Ar Ra'du",
    jumlahRukuk: 6,
    type: "madinah",
    urut: 96
  ),
  Surah(
    id: 14,
    arti: "Ibrahim",
    asma: "ابراهيم",
    jumlahAyat: 52,
    keyword: "ibrahim",
    keterangan: "",
    namaSurah: "Ibrahim",
    jumlahRukuk: 7,
    type: "mekah",
    urut: 72
  ),
  Surah(
    id: 15,
    arti: "Negeri Kaum Samud",
    asma: "الحجر",
    jumlahAyat: 99,
    keyword: "al hijr",
    keterangan: "",
    namaSurah: "Al Hijr",
    jumlahRukuk: 6,
    type: "mekah",
    urut: 54
  ),
  Surah(
    id: 16,
    arti: "Lebah",
    asma: "النحل",
    jumlahAyat: 128,
    keyword: "an nahl",
    keterangan: "",
    namaSurah: "An Nahl",
    jumlahRukuk: 16,
    type: "mekah",
    urut: 70
  ),
  Surah(
    id: 17,
    arti: "Keturunan Isra’il",
    asma: "الإسراء",
    jumlahAyat: 111,
    keyword: "al isra",
    keterangan: "",
    namaSurah: "Al Israa'",
    jumlahRukuk: 12,
    type: "mekah",
    urut: 50
  ),
  Surah(
    id: 18,
    arti: "Gua",
    asma: "الكهف",
    jumlahAyat: 110,
    keyword: "al kahf",
    keterangan: "",
    namaSurah: "Al Kahfi",
    jumlahRukuk: 12,
    type: "mekah",
    urut: 69
  ),
  Surah(
    id: 19,
    arti: "Maryam",
    asma: "مريم",
    jumlahAyat: 98,
    keyword: "maryam",
    keterangan: "",
    namaSurah: "Maryam",
    jumlahRukuk: 6,
    type: "mekah",
    urut: 44
  ),
  Surah(
    id: 20,
    arti: "TaHa",
    asma: "طه",
    jumlahAyat: 135,
    keyword: "ta ha",
    keterangan: "",
    namaSurah: "Thaahaa",
    jumlahRukuk: 8,
    type: "mekah",
    urut: 45
  ),
  Surah(
    id: 21,
    arti: "Nabi-Nabi",
    asma: "الأنبياء",
    jumlahAyat: 112,
    keyword: "al anbiya",
    keterangan: "",
    namaSurah: "Al Anbiyaa",
    jumlahRukuk: 7,
    type: "mekah",
    urut: 73
  ),
  Surah(
    id: 22,
    arti: "Haji",
    asma: "الحج",
    jumlahAyat: 78,
    keyword: "al hajj",
    keterangan: "",
    namaSurah: "Al Hajj",
    jumlahRukuk: 10,
    type: "madinah",
    urut: 103
  ),
  Surah(
    id: 23,
    arti: "Orang-Orang yang Beriman",
    asma: "المؤمنون",
    jumlahAyat: 118,
    keyword: "al muminun",
    keterangan: "",
    namaSurah: "Al Mu'minun",
    jumlahRukuk: 6,
    type: "mekah",
    urut: 74
  ),
  Surah(
    id: 24,
    arti: "Cahaya",
    asma: "النور",
    jumlahAyat: 64,
    keyword: "an nur",
    keterangan: "",
    namaSurah: "An Nuur",
    jumlahRukuk: 9,
    type: "madinah",
    urut: 102
  ),
  Surah(
    id: 25,
    arti: "Pembeda",
    asma: "الفرقان",
    jumlahAyat: 77,
    keyword: "al furqan",
    keterangan: "",
    namaSurah: "Al Furqaan",
    jumlahRukuk: 6,
    type: "mekah",
    urut: 42
  ),
  Surah(
    id: 26,
    arti: "Para Penyair",
    asma: "الشعراء",
    jumlahAyat: 227,
    keyword: "asy syuara",
    keterangan: "",
    namaSurah: "Asy Syu'ara",
    jumlahRukuk: 11,
    type: "mekah",
    urut: 47
  ),
  Surah(
    id: 27,
    arti: "Semut",
    asma: "النمل",
    jumlahAyat: 93,
    keyword: "an naml",
    keterangan: "",
    namaSurah: "An Naml",
    jumlahRukuk: 7,
    type: "mekah",
    urut: 48
  ),
  Surah(
    id: 28,
    arti: "Cerita-Cerita",
    asma: "القصص",
    jumlahAyat: 88,
    keyword: "al qasas",
    keterangan: "",
    namaSurah: "Al Qashash",
    jumlahRukuk: 9,
    type: "mekah",
    urut: 49
  ),
  Surah(
    id: 29,
    arti: "Laba-Laba",
    asma: "العنكبوت",
    jumlahAyat: 69,
    keyword: "al ankabut",
    keterangan: "",
    namaSurah: "Al 'Ankabut",
    jumlahRukuk: 7,
    type: "mekah",
    urut: 85
  ),
  Surah(
    id: 30,
    arti: "Bangsa Romawi",
    asma: "الروم",
    jumlahAyat: 60,
    keyword: "ar rum",
    keterangan: "",
    namaSurah: "Ar Ruum",
    jumlahRukuk: 6,
    type: "mekah",
    urut: 84
  ),
  Surah(
    id: 31,
    arti: "Luqman",
    asma: "لقمان",
    jumlahAyat: 34,
    keyword: "luqman lukman",
    keterangan: "",
    namaSurah: "Luqman",
    jumlahRukuk: 4,
    type: "mekah",
    urut: 57
  ),
  Surah(
    id: 32,
    arti: "Sujud",
    asma: "السجدة",
    jumlahAyat: 30,
    keyword: "as sajdah",
    keterangan: "",
    namaSurah: "As Sajdah",
    jumlahRukuk: 3,
    type: "mekah",
    urut: 75
  ),
  Surah(
    id: 33,
    arti: "Golongan yang Bersekutu",
    asma: "الأحزاب",
    jumlahAyat: 73,
    keyword: "al ahzab",
    keterangan: "",
    namaSurah: "Al Ahzab",
    jumlahRukuk: 9,
    type: "madinah",
    urut: 90
  ),
  Surah(
    id: 34,
    arti: "Kaum Saba’",
    asma: "سبإ",
    jumlahAyat: 54,
    keyword: "saba",
    keterangan: "",
    namaSurah: "Saba'",
    jumlahRukuk: 6,
    type: "mekah",
    urut: 58
  ),
  Surah(
    id: 35,
    arti: "Pencipta",
    asma: "فاطر",
    jumlahAyat: 45,
    keyword: "fatir",
    keterangan: "",
    namaSurah: "Faathir",
    jumlahRukuk: 5,
    type: "mekah",
    urut: 43
  ),
  Surah(
    id: 36,
    arti: "YaSin",
    asma: "يس",
    jumlahAyat: 83,
    keyword: "ya sin yasin",
    keterangan: "",
    namaSurah: "Yaa Siin",
    jumlahRukuk: 5,
    type: "mekah",
    urut: 41
  ),
  Surah(
    id: 37,
    arti: "Yang Bersaf-saf",
    asma: "الصافات",
    jumlahAyat: 182,
    keyword: "as saffat",
    keterangan: "",
    namaSurah: "Ash Shaaffat",
    jumlahRukuk: 5,
    type: "mekah",
    urut: 56
  ),
  Surah(
    id: 38,
    arti: "Sad",
    asma: "ص",
    jumlahAyat: 88,
    keyword: "sad",
    keterangan: "",
    namaSurah: "Shaad",
    jumlahRukuk: 5,
    type: "mekah",
    urut: 38
  ),
  Surah(
    id: 39,
    arti: "Rombongan-Rombongan",
    asma: "الزمر",
    jumlahAyat: 75,
    keyword: "az zumar",
    keterangan: "",
    namaSurah: "Az Zumar",
    jumlahRukuk: 8,
    type: "mekah",
    urut: 59
  ),
  Surah(
    id: 40,
    arti: "Orang yang Beriman",
    asma: "غافر",
    jumlahAyat: 85,
    keyword: "ghafir",
    keterangan: "",
    namaSurah: "Al Ghaafir",
    jumlahRukuk: 9,
    type: "mekah",
    urut: 60
  ),
  Surah(
    id: 41,
    arti: "Ha Mim As-Sajdah",
    asma: "فصلت",
    jumlahAyat: 54,
    keyword: "fussilat",
    keterangan: "",
    namaSurah: "Al Fushilat",
    jumlahRukuk: 6,
    type: "mekah",
    urut: 61
  ),
  Surah(
    id: 42,
    arti: "Musyawarah",
    asma: "الشورى",
    jumlahAyat: 53,
    keyword: "asy syura",
    keterangan: "",
    namaSurah: "Asy Syuura",
    jumlahRukuk: 5,
    type: "mekah",
    urut: 62
  ),
  Surah(
    id: 43,
    arti: "Perhiasan",
    asma: "الزخرف",
    jumlahAyat: 89,
    keyword: "az zukhruf",
    keterangan: "",
    namaSurah: "Az Zukhruf",
    jumlahRukuk: 7,
    type: "mekah",
    urut: 63
  ),
  Surah(
    id: 44,
    arti: "Kabut",
    asma: "الدخان",
    jumlahAyat: 59,
    keyword: "ad dukhan",
    keterangan: "",
    namaSurah: "Ad Dukhaan",
    jumlahRukuk: 3,
    type: "mekah",
    urut: 64
  ),
  Surah(
    id: 45,
    arti: "Yang Berlutut",
    asma: "الجاثية",
    jumlahAyat: 37,
    keyword: "al jasiyah",
    keterangan: "",
    namaSurah: "Al Jaatsiyah",
    jumlahRukuk: 4,
    type: "mekah",
    urut: 65
  ),
  Surah(
    id: 46,
    arti: "Bukit-Bukit Pasir",
    asma: "الأحقاف",
    jumlahAyat: 35,
    keyword: "al ahqaf",
    keterangan: "",
    namaSurah: "Al Ahqaaf",
    jumlahRukuk: 4,
    type: "mekah",
    urut: 66
  ),
  Surah(
    id: 47,
    arti: "Nabi Muhammad SAW",
    asma: "محمد",
    jumlahAyat: 38,
    keyword: "muhammad",
    keterangan: "",
    namaSurah: "Muhammad",
    jumlahRukuk: 4,
    type: "madinah",
    urut: 95
  ),
  Surah(
    id: 48,
    arti: "Kemenangan",
    asma: "الفتح",
    jumlahAyat: 29,
    keyword: "al fath",
    keterangan: "",
    namaSurah: "Al Fath",
    jumlahRukuk: 4,
    type: "madinah",
    urut: 111
  ),
  Surah(
    id: 49,
    arti: "Kamar-Kamar",
    asma: "الحجرات",
    jumlahAyat: 18,
    keyword: "al hujurat",
    keterangan: "",
    namaSurah: "Al Hujuraat",
    jumlahRukuk: 2,
    type: "madinah",
    urut: 106
  ),
  Surah(
    id: 50,
    arti: "Qaf",
    asma: "ق",
    jumlahAyat: 45,
    keyword: "qaf qaaf",
    keterangan: "",
    namaSurah: "Qaaf",
    jumlahRukuk: 3,
    type: "mekah",
    urut: 34
  ),
  Surah(
    id: 51,
    arti: "Angin yang menerbangkan",
    asma: "الذاريات",
    jumlahAyat: 60,
    keyword: "az zariyat dzariyat",
    keterangan: "",
    namaSurah: "Adz Dzaariyaat",
    jumlahRukuk: 3,
    type: "mekah",
    urut: 67
  ),
  Surah(
    id: 52,
    arti: "Bukit",
    asma: "الطور",
    jumlahAyat: 49,
    keyword: "at tur",
    keterangan: "",
    namaSurah: "Ath Thuur",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 76
  ),
  Surah(
    id: 53,
    arti: "Bintang",
    asma: "النجم",
    jumlahAyat: 62,
    keyword: "an najm",
    keterangan: "",
    namaSurah: "An Najm",
    jumlahRukuk: 3,
    type: "mekah",
    urut: 23
  ),
  Surah(
    id: 54,
    arti: "Bulan",
    asma: "القمر",
    jumlahAyat: 55,
    keyword: "al qamar",
    keterangan: "",
    namaSurah: "Al Qamar",
    jumlahRukuk: 3,
    type: "mekah",
    urut: 37
  ),
  Surah(
    id: 55,
    arti: "Yang Maha Pemurah",
    asma: "الرحمن",
    jumlahAyat: 78,
    keyword: "ar rahman",
    keterangan: "",
    namaSurah: "Ar Rahmaan",
    jumlahRukuk: 3,
    type: "madinah",
    urut: 97
  ),
  Surah(
    id: 56,
    arti: "Hari Kiamat",
    asma: "الواقعة",
    jumlahAyat: 96,
    keyword: "al waqiah",
    keterangan: "",
    namaSurah: "Al Waaqi'ah",
    jumlahRukuk: 3,
    type: "mekah",
    urut: 46
  ),
  Surah(
    id: 57,
    arti: "Besi",
    asma: "الحديد",
    jumlahAyat: 29,
    keyword: "al hadid",
    keterangan: "",
    namaSurah: "Al Hadiid",
    jumlahRukuk: 4,
    type: "madinah",
    urut: 94
  ),
  Surah(
    id: 58,
    arti: "Wanita yang Mengajukan Gugatan",
    asma: "المجادلة",
    jumlahAyat: 22,
    keyword: "al mujadilah",
    keterangan: "",
    namaSurah: "Al Mujaadalah",
    jumlahRukuk: 3,
    type: "madinah",
    urut: 105
  ),
  Surah(
    id: 59,
    arti: "Pengusiran",
    asma: "الحشر",
    jumlahAyat: 24,
    keyword: "al hasyr",
    keterangan: "",
    namaSurah: "Al Hasyr",
    jumlahRukuk: 3,
    type: "madinah",
    urut: 101
  ),
  Surah(
    id: 60,
    arti: "Perempuan yang Diuji",
    asma: "الممتحنة",
    jumlahAyat: 13,
    keyword: "al mumtahanah",
    keterangan: "",
    namaSurah: "Al mumtahanah",
    jumlahRukuk: 2,
    type: "madinah",
    urut: 91
  ),
  Surah(
    id: 61,
    arti: "Barisan",
    asma: "الصف",
    jumlahAyat: 14,
    keyword: "as saff",
    keterangan: "",
    namaSurah: "Ash Shaff",
    jumlahRukuk: 2,
    type: "madinah",
    urut: 109
  ),
  Surah(
    id: 62,
    arti: "Hari Jum’at",
    asma: "الجمعة",
    jumlahAyat: 11,
    keyword: "al jumuah",
    keterangan: "",
    namaSurah: "Al Jumuah",
    jumlahRukuk: 2,
    type: "madinah",
    urut: 110
  ),
  Surah(
    id: 63,
    arti: "Orang-Orang yang Munafik",
    asma: "المنافقون",
    jumlahAyat: 11,
    keyword: "al munafiqun",
    keterangan: "",
    namaSurah: "Al Munafiqun",
    jumlahRukuk: 2,
    type: "madinah",
    urut: 104
  ),
  Surah(
    id: 64,
    arti: "Hari Ditampakkan Segala Kesalahan",
    asma: "التغابن",
    jumlahAyat: 18,
    keyword: "at tagabun",
    keterangan: "",
    namaSurah: "Ath Taghabun",
    jumlahRukuk: 2,
    type: "madinah",
    urut: 108
  ),
  Surah(
    id: 65,
    arti: "Talak",
    asma: "الطلاق",
    jumlahAyat: 12,
    keyword: "at talaq",
    keterangan: "",
    namaSurah: "Ath Thalaaq",
    jumlahRukuk: 2,
    type: "madinah",
    urut: 99
  ),
  Surah(
    id: 66,
    arti: "Mengharamkan",
    asma: "التحريم",
    jumlahAyat: 12,
    keyword: "at tahrim",
    keterangan: "",
    namaSurah: "At Tahriim",
    jumlahRukuk: 2,
    type: "madinah",
    urut: 107
  ),
  Surah(
    id: 67,
    arti: "Kerajaan",
    asma: "الملك",
    jumlahAyat: 30,
    keyword: "al mulk",
    keterangan: "",
    namaSurah: "Al Mulk",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 77
  ),
  Surah(
    id: 68,
    arti: "Kalam",
    asma: "القلم",
    jumlahAyat: 52,
    keyword: "al qalam",
    keterangan: "",
    namaSurah: "Al Qalam",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 2
  ),
  Surah(
    id: 69,
    arti: "Hari Kiamat",
    asma: "الحاقة",
    jumlahAyat: 52,
    keyword: "al haqqah",
    keterangan: "",
    namaSurah: "Al Haaqqah",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 78
  ),
  Surah(
    id: 70,
    arti: "Tempa-Tempat Naik",
    asma: "المعارج",
    jumlahAyat: 44,
    keyword: "al maarij",
    keterangan: "",
    namaSurah: "Al Ma'aarij",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 79
  ),
  Surah(
    id: 71,
    arti: "Nuh",
    asma: "نوح",
    jumlahAyat: 28,
    keyword: "nuh",
    keterangan: "",
    namaSurah: "Nuh",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 71
  ),
  Surah(
    id: 72,
    arti: "Jin",
    asma: "الجن",
    jumlahAyat: 28,
    keyword: "al jinn",
    keterangan: "",
    namaSurah: "Al Jin",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 40
  ),
  Surah(
    id: 73,
    arti: "Orang-orang yang Berselimut",
    asma: "المزمل",
    jumlahAyat: 20,
    keyword: "al muzzammil",
    keterangan: "",
    namaSurah: "Al Muzammil",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 3
  ),
  Surah(
    id: 74,
    arti: "Orang yang berkemul",
    asma: "المدثر",
    jumlahAyat: 56,
    keyword: "al muddassir",
    keterangan: "",
    namaSurah: "Al Muddastir",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 4
  ),
  Surah(
    id: 75,
    arti: "Hari Kiamat",
    asma: "القيامة",
    jumlahAyat: 40,
    keyword: "al qiyamah",
    keterangan: "",
    namaSurah: "Al Qiyaamah",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 31
  ),
  Surah(
    id: 76,
    arti: "Manusia",
    asma: "الانسان",
    jumlahAyat: 31,
    keyword: "al insan",
    keterangan: "",
    namaSurah: "Al Insaan",
    jumlahRukuk: 2,
    type: "madinah",
    urut: 98
  ),
  Surah(
    id: 77,
    arti: "Malaikat yang Diutus",
    asma: "المرسلات",
    jumlahAyat: 50,
    keyword: "al mursalat",
    keterangan: "",
    namaSurah: "Al Mursalaat",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 33
  ),
  Surah(
    id: 78,
    arti: "Berita Besar",
    asma: "النبإ",
    jumlahAyat: 40,
    keyword: "an naba",
    keterangan: "",
    namaSurah: "An Naba'",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 80
  ),
  Surah(
    id: 79,
    arti: "Malaikat-Malaikat yang Mencabut",
    asma: "النازعات",
    jumlahAyat: 46,
    keyword: "an naziat",
    keterangan: "",
    namaSurah: "An Naazi'at",
    jumlahRukuk: 2,
    type: "mekah",
    urut: 81
  ),
  Surah(
    id: 80,
    arti: "Ia Bermuka Masam",
    asma: "عبس",
    jumlahAyat: 42,
    keyword: "abasa",
    keterangan: "",
    namaSurah: "'Abasa",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 24
  ),
  Surah(
    id: 81,
    arti: "Menggulung",
    asma: "التكوير",
    jumlahAyat: 29,
    keyword: "at takwir",
    keterangan: "",
    namaSurah: "At Takwiir",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 7
  ),
  Surah(
    id: 82,
    arti: "Terbelah",
    asma: "الإنفطار",
    jumlahAyat: 19,
    keyword: "al infitar",
    keterangan: "",
    namaSurah: "Al Infithar",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 82
  ),
  Surah(
    id: 83,
    arti: "Kecurangan",
    asma: "المطففين",
    jumlahAyat: 36,
    keyword: "al tatfif",
    keterangan: "",
    namaSurah: "Al Muthaffifin",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 86
  ),
  Surah(
    id: 84,
    arti: "Terbelah",
    asma: "الإنشقاق",
    jumlahAyat: 25,
    keyword: "al insyiqaq",
    keterangan: "",
    namaSurah: "Al Insyiqaq",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 83
  ),
  Surah(
    id: 85,
    arti: "Gugusan Bintang",
    asma: "البروج",
    jumlahAyat: 22,
    keyword: "al buruj",
    keterangan: "",
    namaSurah: "Al Buruuj",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 27
  ),
  Surah(
    id: 86,
    arti: "Yang Datang di Malam Hari",
    asma: "الطارق",
    jumlahAyat: 17,
    keyword: "at tariq",
    keterangan: "",
    namaSurah: "Ath Thariq",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 36
  ),
  Surah(
    id: 87,
    arti: "Yang Paling Tinggi",
    asma: "الأعلى",
    jumlahAyat: 19,
    keyword: "al ala",
    keterangan: "",
    namaSurah: "Al A'laa",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 8
  ),
  Surah(
    id: 88,
    arti: "Hari Pembalasan",
    asma: "الغاشية",
    jumlahAyat: 26,
    keyword: "al gasyiyah",
    keterangan: "",
    namaSurah: "Al Ghaasyiah",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 68
  ),
  Surah(
    id: 89,
    arti: "Fajar",
    asma: "الفجر",
    jumlahAyat: 30,
    keyword: "al fajr",
    keterangan: "",
    namaSurah: "Al Fajr",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 10
  ),
  Surah(
    id: 90,
    arti: "Negeri",
    asma: "البلد",
    jumlahAyat: 20,
    keyword: "al balad",
    keterangan: "",
    namaSurah: "Al Balad",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 35
  ),
  Surah(
    id: 91,
    arti: "Matahari",
    asma: "الشمس",
    jumlahAyat: 15,
    keyword: "asy syams",
    keterangan: "",
    namaSurah: "Asy Syams",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 26
  ),
  Surah(
    id: 92,
    arti: "Malam",
    asma: "الليل",
    jumlahAyat: 21,
    keyword: "al lail",
    keterangan: "",
    namaSurah: "Al Lail",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 9
  ),
  Surah(
    id: 93,
    arti: "Waktu Dhuha",
    asma: "الضحى",
    jumlahAyat: 11,
    keyword: "ad duha",
    keterangan: "",
    namaSurah: "Adh Dhuhaa",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 11
  ),
  Surah(
    id: 94,
    arti: "Kelapangan",
    asma: "الشرح",
    jumlahAyat: 8,
    keyword: "al insyirah asy syarh",
    keterangan: "",
    namaSurah: "Asy Syarh",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 12
  ),
  Surah(
    id: 95,
    arti: "Buah Tin",
    asma: "التين",
    jumlahAyat: 8,
    keyword: "at tin tiin",
    keterangan: "",
    namaSurah: "At Tiin",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 28
  ),
  Surah(
    id: 96,
    arti: "Segumpal Darah",
    asma: "العلق",
    jumlahAyat: 19,
    keyword: "al alaq",
    keterangan: "",
    namaSurah: "Al 'Alaq",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 1
  ),
  Surah(
    id: 97,
    arti: "Kemuliaan",
    asma: "القدر",
    jumlahAyat: 5,
    keyword: "al qadr",
    keterangan: "",
    namaSurah: "Al Qadr",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 25
  ),
  Surah(
    id: 98,
    arti: "Bukti yang Nyata",
    asma: "البينة",
    jumlahAyat: 8,
    keyword: "al bayyinah",
    keterangan: "",
    namaSurah: "Al Bayyinah",
    jumlahRukuk: 1,
    type: "madinah",
    urut: 100
  ),
  Surah(
    id: 99,
    arti: "Keguncangan",
    asma: "الزلزلة",
    jumlahAyat: 8,
    keyword: "az zalzalah",
    keterangan: "",
    namaSurah: "Az Zalzalah",
    jumlahRukuk: 1,
    type: "madinah",
    urut: 93
  ),
  Surah(
    id: 100,
    arti: "Kuda Perang yang Berlari Kencang",
    asma: "العاديات",
    jumlahAyat: 11,
    keyword: "al adiyat aadiyah",
    keterangan: "",
    namaSurah: "Al 'Aadiyah",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 14
  ),
  Surah(
    id: 101,
    arti: "Hari Kiamat",
    asma: "القارعة",
    jumlahAyat: 11,
    keyword: "al qariah qaari ah",
    keterangan: "",
    namaSurah: "Al Qaari'ah",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 30
  ),
  Surah(
    id: 102,
    arti: "Bermegah-Megahan",
    asma: "التكاثر",
    jumlahAyat: 8,
    keyword: "at takasur takaatsur",
    keterangan: "",
    namaSurah: "At Takaatsur",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 16
  ),
  Surah(
    id: 103,
    arti: "Masa",
    asma: "العصر",
    jumlahAyat: 3,
    keyword: "al asr",
    keterangan: "",
    namaSurah: "Al 'Ashr",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 13
  ),
  Surah(
    id: 104,
    arti: "Pengumpat",
    asma: "الهمزة",
    jumlahAyat: 9,
    keyword: "al humazah",
    keterangan: "",
    namaSurah: "Al Humazah",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 32
  ),
  Surah(
    id: 105,
    arti: "Gajah",
    asma: "الفيل",
    jumlahAyat: 5,
    keyword: "al fil fiil",
    keterangan: "",
    namaSurah: "Al Fiil",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 19
  ),
  Surah(
    id: 106,
    arti: "Suku Quraysy",
    asma: "قريش",
    jumlahAyat: 4,
    keyword: "quraisy",
    keterangan: "",
    namaSurah: "Quraisy",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 29
  ),
  Surah(
    id: 107,
    arti: "Barang-Barang yang Berguna",
    asma: "الماعون",
    jumlahAyat: 7,
    keyword: "al maun maa uun",
    keterangan: "",
    namaSurah: "Al Maa'uun",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 17
  ),
  Surah(
    id: 108,
    arti: "Nikmat yang Banyak",
    asma: "الكوثر",
    jumlahAyat: 3,
    keyword: "al kausar",
    keterangan: "",
    namaSurah: "Al Kautsar",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 15
  ),
  Surah(
    id: 109,
    arti: "Orang-Orang Kafir",
    asma: "الكافرون",
    jumlahAyat: 6,
    keyword: "al kafirun",
    keterangan: "",
    namaSurah: "Al Kafirun",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 18
  ),
  Surah(
    id: 110,
    arti: "Pertolongan",
    asma: "النصر",
    jumlahAyat: 3,
    keyword: "an nasr nashr",
    keterangan: "",
    namaSurah: "An Nashr",
    jumlahRukuk: 1,
    type: "madinah",
    urut: 114
  ),
  Surah(
    id: 111,
    arti: "Gejolak Api",
    asma: "المسد",
    jumlahAyat: 5,
    keyword: "al lahab",
    keterangan: "",
    namaSurah: "Al Lahab",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 6
  ),
  Surah(
    id: 112,
    arti: "Kemurnian Keesaan Allah",
    asma: "الإخلاص",
    jumlahAyat: 4,
    keyword: "al ikhlas iklas",
    keterangan: "",
    namaSurah: "Al Ikhlash",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 22
  ),
  Surah(
    id: 113,
    arti: "Waktu Subuh",
    asma: "الفلق",
    jumlahAyat: 5,
    keyword: "al falaq",
    keterangan: "",
    namaSurah: "Al Falaq",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 20
  ),
  Surah(
    id: 114,
    arti: "Manusia",
    asma: "الناس",
    jumlahAyat: 6,
    keyword: "an nas naas",
    keterangan: "",
    namaSurah: "An Naas",
    jumlahRukuk: 1,
    type: "mekah",
    urut: 21
  )
};